Issue92 favoriten
MaxTrautwein/AStA-Digital-Forms pull request #101
Opened 2024-05-31 23:06 UTC by Ebenezer2077

hoffentlich fürs erste ausreichend, weil ich nicht weiß, ob ich übers wochenende nochmal dazu komme

2024-06-01 08:06 UTC, MaxTrautwein commented on Backend/src/main/java/de/PSWTM/DigitalForms/controller/FavouriteController.java
> +        return ResponseEntity.ok().build();
I would want to see some checks here if the User can actually Delete that ID

1. Does that ID Exist?
2. Is the User the Owner

2024-06-01 08:07 UTC, MaxTrautwein commented on Backend/src/main/java/de/PSWTM/DigitalForms/controller/FavouriteController.java
> +    public ResponseEntity<Favourite> favouritesFavIdGet(String favId) {
is that not needed?
_as it is not implemented_

2024-06-01 08:09 UTC, MaxTrautwein commented on Frontend/src/app/collapsable-bottom/collapsable-bottom.component.html
> -  </div>
Würde das nicht entfernen, da noch keine Alternative existiert

2024-06-01 08:14 UTC, MaxTrautwein commented on Frontend/src/app/collapsable-bottom/marked-item/marked-item.component.ts
I don't like that the Load Feature gets removed without being added at an alternative location

2024-06-01 08:16 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.html
> +    @if(!this.isInFav()) {
Ich denke das wäre mit nem else verständlicher

2024-06-01 08:25 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.html
> +      <button class="fav-button" (click)="this.FavService.putFav(this.form.id!);">
That confuses me why use the ID?
Didn't we add `parent` for that!?

also use `FormDetail.` not the private var

2024-06-01 08:25 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.html
> +      <button class="fav-button" (click)="this.FavService.delFav(this.getFavId()!);">
That confuses me why use the ID?
Didn't we add `parent` for that!?

also use `FormDetail.` not the private var

2024-06-01 08:27 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.html
For modularity and better Structure, I would like to see the Favorites code in its own component

2024-06-01 08:27 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.ts
> +  protected form!: Form;
why change that?

2024-06-01 08:28 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.ts
> +  constructor(private route: ActivatedRoute, protected templateService: TemplateService,
why change that to protected?

2024-06-01 08:29 UTC, MaxTrautwein requested changes
See comments

2024-06-01 08:50 UTC, MaxTrautwein commented
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/9217909c-d1f9-4f9e-89ab-3641f0874b48)
Schade, dass das nicht responsive ist.

Muss zurück und wieder darauf, dass das wechselt

2024-06-01 08:54 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.html
> +      <button class="fav-button" (click)="this.FavService.delFav(this.getFavId()!);">
That implementation also allows Saving Filled forms
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/4afc5b6d-1425-46dd-9b2c-843fa3580c60)
& that doesn't look good

2024-06-01 08:55 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.html
> +      <button class="fav-button" (click)="this.FavService.putFav(this.form.id!);">
That implementation also allows Saving Filled forms
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/4afc5b6d-1425-46dd-9b2c-843fa3580c60)
& that doesn't look good

2024-06-01 08:57 UTC, MaxTrautwein commented
Current look
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/6df1ff91-191f-447e-b6ba-8a45d24717eb)

2024-06-03 14:21 UTC, Ebenezer2077 commented on Frontend/src/app/form-container/form-container.component.ts
> +  protected form!: Form;
geht nich anders, weil ich das im html teil brauche, FormDetails geht anscheinend nich, weil das Frontend nicht mit Promisses klarkommt

2024-06-03 14:21 UTC, Ebenezer2077 commented
should be ready for merge now

2024-06-03 15:57 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-container.component.ts
> +  protected form!: Form;
? das ist koomich, weil ich mach das mit dem Promise
 Sihe: https://github.com/MaxTrautwein/AStA-Digital-Forms/pull/101/files#diff-c37abd6247d67dc75db0c946eaa7a3f4c20805f0716bd421f47ab2d3ae0f89faR1

2024-06-03 16:59 UTC, MaxTrautwein commented
hmm das schaute etwas dof aus
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/3154009f-8be7-475d-aca1-7708bbc36c17)

2024-06-03 19:10 UTC, Ebenezer2077 commented on Frontend/src/app/form-container/form-container.component.ts
> +  protected form!: Form;
bei mir hats nich funktioniert...

2024-06-03 19:11 UTC, Ebenezer2077 commented on Backend/src/main/java/de/PSWTM/DigitalForms/controller/FavouriteController.java
> +    public ResponseEntity<Favourite> favouritesFavIdGet(String favId) {
ich glaube nicht, dass das im Moment gebraucht wird, aber in Zukunft vielleicht. Soll ichs trotzdem rauswerfen?

2024-06-03 21:27 UTC, MaxTrautwein commented on Backend/src/main/java/de/PSWTM/DigitalForms/controller/FavouriteController.java
> +    public ResponseEntity<Favourite> favouritesFavIdGet(String favId) {
kann noch warten

2024-06-03 21:31 UTC, MaxTrautwein approved these changes
Da GUI noch nachgebessert wird, denke ich, dass das rein kann

2024-06-03 21:39 UTC, MaxTrautwein commented
Hoffe es tut noch

2024-06-03 21:42 UTC, merged