Textfelder im Antrag
MaxTrautwein/AStA-Digital-Forms pull request #103
Opened 2024-06-04 03:07 UTC by HydroZocker

2024-06-04 03:07 UTC, HydroZocker commented
Arbeitszeit bis jetzt 6h

2024-06-04 04:50 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-content/form-content.component.html
Hier fehlt die Übergabe der Werte komplett.
d.h.: Die Beschreibung & Hilfe kann nicht angezeigt werden & nichts wird gespeichert

2024-06-04 04:51 UTC, MaxTrautwein requested changes
see comments

2024-06-04 05:07 UTC, MaxTrautwein commented
Feedback für ... _(abgesehen von https://github.com/MaxTrautwein/AStA-Digital-Forms/pull/103#discussion_r1625340430)_
Money: Input-Validation wäre nett
Datum: dd/mm/yyyy oder dd.mm.yyyy
"Postleitzahl": Nur Zahlen sollten erlaubt sein, Input-Validation wäre nett
MultiTextFeld: ist viel zu klein. Eventuell user erlauben es zusätzlich noch größer zu machen
Bool: Schaut dof aus

2024-06-06 01:50 UTC, HydroZocker commented
Arbeitszeit 4h für die neusten Commits

2024-06-06 06:54 UTC, MaxTrautwein commented on Frontend/src/app/form-container/form-content/address/address.component.ts
> +  validatePostalCode(value: string): boolean {
also der Funktionsname ist eher missliding
das ist ja eher is a number als alles andere

2024-06-07 18:06 UTC, MaxTrautwein commented
das schaut etwas arg wild aus
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/2f6e26fb-5fc2-416f-9c54-c57da3b21263)
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/15d1b143-5087-4ff8-ae6a-191f61d4871c)
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/a924520c-4e5b-45c9-a6b5-06b21bc65213)

auch etwa uneinheitlich
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/e38c910f-f268-4b77-bcc0-f8e38ba30f09)

von anfang an gesetzt
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/a79e5479-8873-4292-bbce-1427fde5e1cc)

2024-06-07 18:29 UTC, MaxTrautwein commented
nochmal neu gepullet, immernoch erros & jetzt auch noch mit wilder farb wahl
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/dca1ae5c-c62f-461c-98b8-19e149fe73a7)

2024-06-07 18:35 UTC, HydroZocker commented
Die Farbwahl ist fürs Design Update bzw. der Anfang davon. Hab überlegt die Boxen Blau zu machen für Bsp. Description, damit es nicht stumpf schwarz weiß ist

2024-06-07 18:55 UTC, MaxTrautwein commented
Straße ist viel zu winzig
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/d75332ab-53eb-48a5-9654-c517efd7f7c0)

2024-06-07 18:58 UTC, MaxTrautwein commented
Speichern vom bool tut nicht

2024-06-08 16:25 UTC, MaxTrautwein commented
Still Inconsistent Display
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/e9c6bcec-48a5-4a28-89f7-25839de1b5bc)

2024-06-08 16:26 UTC, MaxTrautwein commented
Immer noch zu klein & Posi der Beschreibung ungünstig
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/dd368a35-56db-4e49-b709-8f5e97ef1186)

2024-06-08 16:27 UTC, MaxTrautwein commented
Wieso ist die PLZ so mega lang?
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/a8c5a65b-6284-4b43-8d38-ec659cc9b45b)

2024-06-08 16:28 UTC, MaxTrautwein requested changes
mache Help Texts sind Itallic andere nicht

2024-06-08 16:31 UTC, HydroZocker commented
Gewünschte Änderungen werden bald übernommen.

2024-06-09 22:15 UTC, MaxTrautwein commented
Etwas breiter als default wäre gut.
Scaleing tut beim laden nicht.
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/ec34a90f-ec22-4ada-b538-f7ac70cab35d)

2024-06-09 22:34 UTC, MaxTrautwein commented
bei `Ausgaben und Anschaffungen`
seinen `Spätester Termin für die Rückzahlung` & `Termin (geplant):` verbunden zu sein. Das sollte nicht der fall ein.
Nach einem Reload tut es.

Fehler vermutlich in / durch `ngAfterViewInit`. Korekter Wert wird übergeben

2024-06-09 22:38 UTC, MaxTrautwein commented
With dac6e456b724e4edd0d30b4978610a2cf35ceb9b manual resize works, but it is hardly any larger
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/45c14d9b-751d-4c46-8553-724b21b70293)

_typing a char appears to trigger the scaling_

2024-06-10 09:05 UTC, MaxTrautwein commented
Last two comments are resolved.
Awaiting fix for all new elements

2024-06-10 09:10 UTC, MaxTrautwein commented
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/35b8c615-7482-4ebb-ad9f-6a6a8c93be99)
![image](https://github.com/MaxTrautwein/AStA-Digital-Forms/assets/46843360/d5e081ef-325f-41de-b68c-ddc5d7b2c392)

Komma zahlen sollten erlaubt sein
Ein Minus am Anfang sollte generell auch möglich sein

2024-06-11 07:06 UTC, MaxTrautwein commented on Frontend/package.json
> +    "angular-iban": "^17.0.0",
Das bitte entfernen, da es nicht verwendet wird.

_ja das geht_

2024-06-11 07:07 UTC, MaxTrautwein commented on Frontend/package.json
> +    "iban": "^0.0.14",
Das bitte entfernen, da es nicht verwendet wird.

_ja das geht_

2024-06-11 07:08 UTC, MaxTrautwein requested changes
nach dem Löschen der nicht benötigten Pakete, kann man es mergen

2024-06-11 10:54 UTC, merged