Projektmanagment Doku
MaxTrautwein/AStA-Digital-Forms pull request #13
Opened 2024-04-05 10:58 UTC by HydroZocker

Doku vollständig bearbeitet.

2024-04-05 11:02 UTC, MaxTrautwein requested changes
Please check the comments

2024-04-05 11:02 UTC, MaxTrautwein commented on Doc/main.tex
> +   \include{paragraphs/Projektmanagement}
Seems unintentional, maybe remove that

2024-04-05 11:02 UTC, MaxTrautwein commented on package-lock.json
Please remove that file

2024-04-05 11:39 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
>  \section{Methode}\label{sec:methode}
Hätte gedacht, dass wir hier nennen nach welcher Methode wir arbeiten, eventuell mit Begründung und oder Erklärungen.
Sehe hier allerdings nur ein Beispiel für eine agile Methode genannt.

2024-04-05 11:41 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Durch die GNU GPL v3.0 bleibt der Code frei zugänglich und schützt gleichzeitig die Rechte der Nutzer und Entwickler.
Was für Rechte von Nutzern schützen wir?
_also wäre mir jetzt nicht bewusst, bin allerdings auch kein experte..._

2024-04-05 11:44 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Die Kriterien dieses Projekts bestehen zusammengefasst aus einem voll funktionsfähigen Code, sinnvoll kommentierten Code, Erstellung von Tests, erfolgreichen Tests und einer vollständigen Dokumentati
hmm etwas verwirrt hier.
ist das nachfolgende eine Erklärung oder eine ungewollte dopplung?

2024-04-05 11:45 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Für jede Funktion muss es einen Test geben. Ein Test kann auch mehrere Funktionen abdecken. Alle Tests müssen bestanden sein.
Ich meinte mich zu erinnern, dass wir uns noch einigen wollten, was wir genau testen wollen und in welcher form.

2024-04-05 12:29 UTC, HydroZocker commented on Doc/paragraphs/Projektmanagement.tex
>  \section{Methode}\label{sec:methode}
Da wir gesagt haben, dass wir nur agil arbeiten, aber keine feste agile Methode beschlossen wurde habe ich allgemein eine agile Arbeitsweise erklärt.

2024-04-05 12:30 UTC, HydroZocker commented on Doc/paragraphs/Projektmanagement.tex
> +Für jede Funktion muss es einen Test geben. Ein Test kann auch mehrere Funktionen abdecken. Alle Tests müssen bestanden sein.
Da war ich mir selber unschlüssig. In Rücksprache mit Tobi habe ich das so geschrieben.

2024-04-06 14:16 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
>  \section{Methode}\label{sec:methode}
Gerade im Team Scrum Beschlossen

2024-04-08 06:49 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Scrum ist iterativ und agil. Das bedeutet es gibt wiederholende Sprint-Zyklen, bei der das klassische Waterfall-Prinzip geeint wird.
Irgendwie verstehe ich den zweiten Satz nicht

2024-04-08 07:08 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Die Definition of Done beschreibt Kriterien, die abgedeckt sein müssen, damit ein Sprint als abgeschlossen gilt.
Sicher das die DoD für den Sprint gilt und nicht für jeden Task einzeln?
https://www.it-agile.de/agiles-wissen/agile-arbeit/was-ist-eine-definition-of-done/

2024-04-08 16:44 UTC, MaxTrautwein approved these changes
Abgesehen von den geringfügigen Mängeln okay für den merge.
Kann das auch im Zuge von #18 fixen, falls du das nicht extra korrigieren willst

2024-04-08 16:44 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +
Scheinen unnötig

2024-04-08 16:44 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Scrum ist iterativ und agil. Das bedeutet es gibt wiederholende Sprint-Zyklen
`.` am ende fehlt

2024-04-08 16:44 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Der Code muss, die in den Requierements beschriebenen Funktionen lauffähig beinhalten.\\
Meine Rechtschreibprüfung beschwert sich über `Requierements` -> Requirements

2024-04-08 16:44 UTC, MaxTrautwein commented on Doc/paragraphs/Projektmanagement.tex
> +Für jede Task muss es einen Test geben. Ein Test kann auch mehrere Tasks abdecken. Alle Tests müssen bestanden sein.
jeden

2024-04-08 17:00 UTC, merged