Issue 35 ausblick
MaxTrautwein/AStA-Digital-Forms pull request #136
Opened 2024-06-20 15:08 UTC by Ebenezer2077

Should be good to go

2024-06-20 17:57 UTC, MaxTrautwein commented on Doc/paragraphs/Mockups.tex
huch was ist denn da passiert?

2024-06-20 18:02 UTC, MaxTrautwein requested changes
glaub da ist was sief gelaufen.
ab 2462c83396953c460c99ce8b6593ae88e4349416 wurde die falsche datei verändert

2024-06-21 06:25 UTC, MaxTrautwein commented on Doc/paragraphs/Ausblick.tex
hier fehlt jetzt aber ne menge inhaltlich, von dem was du gemacht hast

2024-06-21 06:25 UTC, MaxTrautwein requested changes
vergess den rest nicht

2024-06-21 11:43 UTC, MaxTrautwein commented on Doc/paragraphs/Ausblick.tex
> +\ref{sec: ui design} genannten Interviews entschieden werden.
Bei dem Teil bezweifle ich immer noch, dass das gewollt ist

2024-06-21 11:45 UTC, MaxTrautwein commented on Doc/paragraphs/Mockups.tex
more or less resolved

2024-06-21 11:45 UTC, Ebenezer2077 commented on Doc/paragraphs/Ausblick.tex
> +\ref{sec: ui design} genannten Interviews entschieden werden.
Es is n Feature, mit dem man die Applikation sinnvoll erweitern könnte, das is doch genau das, was der Ausblick sein sollte oder hab ich das falsch verstanden?

2024-06-21 11:56 UTC, MaxTrautwein commented on Doc/paragraphs/Ausblick.tex
> +\ref{sec: ui design} genannten Interviews entschieden werden.
`sinnvoll` ist hier der Knackpunkt. Ich denke dass Google und Co das eher nicht sind.
Allerhöchsten eventuell HS SSO.

Der Hintergrund wäre hier hauptsächlich rechtlicher Natur. 

_Da ich mir hier nicht allzu sicher bin hab ich mal nachgefragt. das war jetzt aber mein verständniss dazu_

2024-06-21 12:16 UTC, MaxTrautwein commented on Doc/paragraphs/Ausblick.tex
> +\ref{sec: ui design} genannten Interviews entschieden werden.
wenn wir das auf das HS SSO statt Google anpassen wäre ich dabei

2024-06-21 12:26 UTC, Ebenezer2077 commented on Doc/paragraphs/Ausblick.tex
> +\ref{sec: ui design} genannten Interviews entschieden werden.
alles klar, mach ich später noch

2024-06-21 17:30 UTC, MaxTrautwein approved these changes
schaut gut aus

2024-06-21 17:51 UTC, merged