WIP - Technology Description
MaxTrautwein/AStA-Digital-Forms pull request #41
Opened 2024-04-25 07:41 UTC by MaxTrautwein

resolves #28

2024-04-27 23:30 UTC, Ebenezer2077 commented on Doc/paragraphs/Techno.tex
> +In diesem Kapitän sind die verwendeten Technologien und Frameworks benannt, erklärt
ich glaube der Kapitän is duch die Rechtschreibprüfung geschlüpft XD

2024-04-27 23:33 UTC, Ebenezer2077 commented on Doc/paragraphs/Techno.tex
> +Zusätzlich wird Benutzerföderation, stake Authentifizierung sowie eine Feine Autorisierung bereitgestellt.
was is mit Benutzerförderation gemeint?

2024-04-27 23:36 UTC, Ebenezer2077 requested changes
Rechtschreib und Gramatik prüfung muss noch gemacht werden, und über die angemerkten Stellen drüber schauen.

2024-04-28 09:13 UTC, MaxTrautwein commented on Doc/paragraphs/Techno.tex
> +Zusätzlich wird Benutzerföderation, stake Authentifizierung sowie eine Feine Autorisierung bereitgestellt.
https://de.wikipedia.org/wiki/F%C3%B6derierte_Identit%C3%A4t
eventuell getrennt schreiben oder ich finde noch ein besseres Wort

2024-04-28 09:42 UTC, MaxTrautwein commented on Doc/paragraphs/Techno.tex
> +In diesem Kapitän sind die verwendeten Technologien und Frameworks benannt, erklärt
behoben

2024-04-28 09:46 UTC, MaxTrautwein commented on Doc/paragraphs/Techno.tex
> +Zusätzlich wird Benutzerföderation, stake Authentifizierung sowie eine Feine Autorisierung bereitgestellt.
`Benutzer-Föderation` besser?

2024-04-28 09:47 UTC, MaxTrautwein commented on Doc/paragraphs/Techno.tex
> +Zusätzlich wird Benutzerföderation, stake Authentifizierung sowie eine Feine Autorisierung bereitgestellt.
Eventuell sollte das ins Glossar.
Was meint ihr @Ebenezer2077 @HydroZocker

2024-04-28 11:46 UTC, Ebenezer2077 commented on Doc/paragraphs/Techno.tex
> +Zusätzlich wird Benutzerföderation, stake Authentifizierung sowie eine Feine Autorisierung bereitgestellt.
muss denk ich auf jeden Fall ins Glosar, weil ich hab noch nie was davon gehört. Aber scheint zu passen

2024-04-28 12:23 UTC, Ebenezer2077 commented
Ich geh selber nochmal über die Rechtschreibung drüber und comitte das dann, aber ansonsten passts

2024-04-28 14:04 UTC, merged